### ISSUE TITLE
Sync pyproj version with pypi

### ISSUE THREAD

**Issue by cheginit** [conda-forge/owslib-feedstock#33]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

A while ago I opened an [issue](https://github.com/geopython/OWSLib/issues/823) on the main owslib repo regarding `pyproj` version. This issue has been addressed in 0.27.2 version on `pypi` by removing `pyproj` as a dependency altogether. But in the conda-forge version, `pyproj` is still limited to <3.3.0. So, `pyproj` should either be removed from `meta.yml` to match the pypi version or it's upper limited should be removed.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by ocefpaf** [comment]
Do you want to send a PR to fix that? It should remove the pyproj line and bump the build number.

**Comment by cheginit** [comment]
Sure!
